name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: echo "$PWD/Example"
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: yanamura/ios-bump-version@v1
      with:
        version: 1.1.0
        project-path: "${PWD}/Example"
    - name: Push bump-version
      run: |
        git add .
        git commit -m "bump version"
        git push origin HEAD
