name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild build
      run: |
        pod install --repo-update --clean-install
        xcodebuild -configuration Release clean build -project Example/Example.xcodeproj -scheme Example -destination "platform=iOS Simulator,name=iPhone 11 Pro"
        
